import pc from "picocolors";

export function runHelp(): void {
  const lines = [
    "",
    pc.bold("nexaed") + " — Nexa Education Platform CLI",
    "",
    pc.bold("Usage:"),
    "  create-nexaed-app [command] [options]",
    "",
    pc.bold("Commands:"),
    `  ${pc.cyan("init")} [name]            Scaffold a new Nexa-connected school app ${pc.dim("(default)")}`,
    `  ${pc.cyan("doctor")}                 Check an existing app for config issues`,
    `  ${pc.cyan("upgrade")}                Upgrade @nexa-ed/* packages to latest`,
    `  ${pc.cyan("skill")}                  Install the Nexa-Ed Claude Code skill into .claude/skills`,
    `  ${pc.cyan("telemetry")} [on|off]     View or change telemetry preference`,
    `  ${pc.cyan("help")}                   Show this help`,
    "",
    pc.bold("Flags (for init) — all optional, the CLI prompts for anything missing:"),
    "  --auth <provider>      workos | clerk | nextauth | none",
    "  --features <list>      Comma-separated: fileProcessing, payments, convex, emailProvisioning",
    "  --ui <library>         shadcn | none",
    "  --email-tier <tier>    tier-1-nexa | tier-2-stalwart | tier-3-google",
    "  --email-domain <host>  e.g. myschool.nexa-ed.com",
    "  --api-key <key>        Nexa API key (nxa_live_…)",
    "  --no-install           Skip dependency install after scaffolding",
    "  --pm <manager>         pnpm | yarn | npm | bun  (auto-detected by default)",
    "  --no-git               Skip `git init`",
    "  --pin <version>        Keep this version — skip the hand-off to the newest release",
    "",
    pc.bold("Environment variables (same effect as the flags):"),
    pc.dim(
      [
        "  NEXAED_PROJECT_NAME  NEXAED_AUTH  NEXAED_UI  NEXAED_FEATURES",
        "  NEXAED_EMAIL_TIER    NEXAED_EMAIL_DOMAIN  NEXAED_API_KEY",
        "  NEXAED_PM            NEXAED_GIT           NEXAED_NO_INSTALL",
        "",
        "  NEXAED_SKIP_UPDATE_CHECK=1   Keep this version instead of handing off to",
        "                               the newest release.",
      ].join("\n"),
    ),
    "",
    pc.bold("Examples:"),
    pc.dim("  # Interactive — nothing else to type"),
    "  create-nexaed-app my-school",
    "",
    pc.dim("  # Fully non-interactive (CI)"),
    "  create-nexaed-app my-school --auth clerk --features convex,payments --no-install",
    "",
    pc.dim("  # Same, via env vars (no flags on the command line)"),
    "  NEXAED_AUTH=clerk NEXAED_FEATURES=convex,payments create-nexaed-app my-school",
    "",
    pc.dim("  # Check an existing project"),
    "  cd my-school && create-nexaed-app doctor",
    "",
    `  Docs: ${pc.underline("https://docs.nexa-ed.com")}`,
    "",
  ];

  console.log(lines.join("\n"));
}
